version: "3.8"
services:
  mongodb:
    container_name: mongo-service
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok" , "localhost:27017/test", "--quiet"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 10s

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "31100:8080"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] # Assuming your backend has a /health endpoint
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"] # Assuming your frontend has a /health endpoint
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  redis:
    container_name: redis-service
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
      - 6379
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  data:
