@Library('Shared') _
pipeline {
    agent {label 'Node'}
    
    environment{
        SONAR_HOME = tool "Sonar"
    }
    
    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Setting docker image for latest push')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Setting docker image for latest push')
    }
    
    stages {
        stage("Validate Parameters") {
            steps {
                script {
                    if (params.FRONTEND_DOCKER_TAG == '' || params.BACKEND_DOCKER_TAG == '') {
                        error("FRONTEND_DOCKER_TAG and BACKEND_DOCKER_TAG must be provided.")
                    }
                }
            }
        }
        stage("Workspace cleanup"){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script{
                    code_checkout("https://github.com/LondheShubham153/Wanderlust-Mega-Project.git","main")
                }
            }
        }
        
        stage("Trivy: Filesystem scan"){
            steps{
                script{
                    trivy_scan()
                }
            }
        }

        stage("OWASP: Dependency check"){
            steps{
                script{
                    owasp_dependency()
                }
            }
        }
        
        stage("SonarQube: Code Analysis"){
            steps{
                script{
                    sonarqube_analysis("Sonar","wanderlust","wanderlust")
                }
            }
        }
        
        stage("SonarQube: Code Quality Gates"){
            steps{
                script{
                    sonarqube_code_quality()
                }
            }
        }
        

        stage("Docker: Build Images") {
            steps {
                script {
                    dir('backend') {
                        sh """
                        docker build -t localhost:5000/wanderlust-backend-beta:${params.BACKEND_DOCKER_TAG} .
                        """
                    }
                    dir('frontend') {
                        sh """
                        docker build -t localhost:5000/wanderlust-frontend-beta:${params.FRONTEND_DOCKER_TAG} .
                        """
                    }
                }
            }
        }

        stage("Docker: Push to Local Registry") {
            steps {
                script {
                    sh "docker push localhost:5000/wanderlust-backend-beta:${params.BACKEND_DOCKER_TAG}"
                    sh "docker push localhost:5000/wanderlust-frontend-beta:${params.FRONTEND_DOCKER_TAG}"
                }
            }
        }

    post{
        success{
            echo "Build completed successfully."
            // archiveArtifacts artifacts: '*.xml', followSymlinks: false
            // build job: "Wanderlust-CD", parameters: [
            //     string(name: 'FRONTEND_DOCKER_TAG', value: "${params.FRONTEND_DOCKER_TAG}"),
            //     string(name: 'BACKEND_DOCKER_TAG', value: "${params.BACKEND_DOCKER_TAG}")
            // ]
        }
    }
}
